### ISSUE TITLE
lemma variant со скобочками

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/tei-abaev#1]
Добавляю, чтобы не забыть исправить потом
![image](https://user-images.githubusercontent.com/13102259/154688824-f6d9b48d-90f4-44af-844e-e3a766737c5f.png)

(Еще там вопрос в двух местах к переводу)

![image](https://user-images.githubusercontent.com/13102259/154688893-1eca6577-eb6e-4191-bdf9-604498eaf576.png)
The tracing back to ratu- is justified, as it would seem, not only by Avestan ratu-, but also by a Digor form radu-gaj 'in turn', however, -u- in this form may be an epenthetical vowel with no etymological significance.

**Comment by obelyaev** [comment]
Сделал в этом репозитории (741d0232984f040b5bbfd3fedf7801bf98de42bc), надо будет ещё сделать в CSS, чтоб рисовал

**Comment by obelyaev** [comment]
Готово.
